name: testdev

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Single deploy job since we're just deploying
  deploy_on_testdev:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Deploy to test server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TESTDEV }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST_TESTDEV }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME_TESTDEV }}
          TARGET: /var/www/vps-back
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al
            echo $RSYNC_STDOUT
            cd /var/www/vps-back
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
